# Generated by Django 3.0.3 on 2021-04-19 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketingsystem', '0002_auto_20210419_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='createdBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdByTechnician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updatedBy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedByTechnician', to=settings.AUTH_USER_MODEL),
        ),
    ]
