# Generated by Django 3.0.3 on 2021-05-03 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingsystem', '0004_auto_20210420_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=150, verbose_name='Item Name')),
                ('itemType', models.CharField(choices=[('Mobile Phone', 'Mobile Phone'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Games Console', 'Games Console'), ('Tablet', 'Tablet'), ('Smart device', 'Smart Device'), ('Monitor', 'Monitor'), ('Peripherals', 'Peripherals'), ('Component', 'Component'), ('Accessory', 'Accessory'), ('Software', 'Software'), ('Other', 'Other')], max_length=50, verbose_name='Item Type')),
                ('quantityInStock', models.IntegerField(verbose_name='In Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('orderLink', models.URLField(blank=True, verbose_name='Order Link')),
                ('lastOrdered', models.DateTimeField(auto_now=True, verbose_name='Last Ordered On')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digits format '00000000000'", regex='^\\d{11}$')], verbose_name='Phone Number'),
        ),
    ]
