# Generated by Django 3.0.3 on 2021-05-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingsystem', '0006_inventoryitem_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemImage',
            field=models.ImageField(blank=True, upload_to='images/stock', verbose_name='Item Picture'),
        ),
    ]
