# Generated by Django 3.0.3 on 2021-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingsystem', '0009_auto_20210527_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemImage',
            field=models.ImageField(blank=True, upload_to='stock/', verbose_name='Item Picture'),
        ),
    ]
