# Generated by Django 3.0.3 on 2021-05-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingsystem', '0010_auto_20210527_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='itemImage',
        ),
    ]
