# Generated by Django 3.0.3 on 2021-06-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingsystem', '0011_remove_inventoryitem_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantityInStock',
            field=models.PositiveIntegerField(verbose_name='In Stock'),
        ),
    ]
